package com.example.ui.theme

import androidx.compose.ui.graphics.Color

object Colors {
    val primary = Color(0xFF1A73E8)
    val primaryText = Color(0xFFFFFFFF)
    val primaryDark = Color(0xFF1557B0)
    val primaryLight = Color(0xFFE8F0FE)
    val background = Color(0xFFF5F5F5)
    val surface = Color(0xFFFFFFFF)
    val border = Color(0xFFE0E0E0)
    val divider = Color(0xFFF0F0F0)
    val textPrimary = Color(0xFF0F172A)
    val textSecondary = Color(0xFF1E293B)
    val textTertiary = Color(0xFF334155)
    val textOnPrimary = Color(0xFFFFFFFF)
    val inputBackground = Color(0xFFFFFFFF)
    val inputText = Color(0xFF0F172A)
    val inputPlaceholder = Color(0xFF334155)
    val inputBorder = Color(0xFFCBD5E1)
    val inputBorderFocus = Color(0xFF1A73E8)
    val labelText = Color(0xFF1E293B)
    val headerBackground = Color(0xFFFFFFFF)
    val headerText = Color(0xFF1A1A1A)
    val cardBackground = Color(0xFFFFFFFF)
    val cardBorder = Color(0xFFEEEEEE)
    val tabBarBackground = Color(0xFFFFFFFF)
    val tabBarActive = Color(0xFF1A73E8)
    val tabBarInactive = Color(0xFFAAAAAA)
    val success = Color(0xFF28A745)
    val danger = Color(0xFFDC3545)
    val warning = Color(0xFFFFA500)
    val info = Color(0xFF17A2B8)
    val drBalance = Color(0xFFDC3545)
    val crBalance = Color(0xFF28A745)
    val badgeSale = Color(0xFFE8F5E9)
    val badgeSaleText = Color(0xFF2E7D32)
    val badgePurchase = Color(0xFFFFF3E0)
    val badgePurchaseText = Color(0xFFE65100)
    val badgeReturn = Color(0xFFFCE4EC)
    val badgeReturnText = Color(0xFFC62828)
    val badgeReceipt = Color(0xFFE3F2FD)
    val badgeReceiptText = Color(0xFF1565C0)
    val badgePayment = Color(0xFFF3E5F5)
    val badgePaymentText = Color(0xFF6A1B9A)
}
